[package]
name = "ironrdp-mcs"
version = "0.1.0"
readme = "README.md"
description = "T.125 MCS implementation for IronRDP"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[features]
default = []
std = ["alloc", "ironrdp-error/std", "ironrdp-common/std"]
alloc = ["ironrdp-error/alloc", "ironrdp-common/alloc"]

[dependencies]
ironrdp-error.workspace = true
ironrdp-common.workspace = true
