[package]
name = "ironrdp_client"
version = "0.1.0"
edition = "2018"
readme = "README.md"
license = "MIT/Apache-2.0"
homepage = "https://github.com/Devolutions/IronRDP"
repository = "https://github.com/Devolutions/IronRDP"
authors = ["Marc-André Moreau <mamoreau@devolutions.net>",
           "Vladyslav Hordiienko <hord.vlad@gmail.com"]
keywords = ["rdp", "client", "remote", "desktop", "protocol"]

[dependencies]
ironrdp = { path = "../ironrdp" }
sspi = { path = "../../sspi-rs" }
clap = "2.33"
bytes = "0.4"
failure = "0.1"
chrono = "0.4"
fern = "0.5"
log = "0.4"
rustls = { version = "0.16.0", features = ["dangerous_configuration"] }
x509-parser = "0.6.0"
whoami = "0.5"
winit = "0.20.0-alpha2"
num-traits = "0.2"
semver = "0.9"
lazy_static = "1.3"
exitcode = "1.1"
webpki = "0.21.0"
bufstream = "0.1"
